# Docling PDF 파싱 성능 검증 (Parsing Evaluation / PoC)

이 노트북은 **PDF → Markdown 변환 테스트가 아니다.** Docling이 PDF의 문서 구조를 얼마나 정확히
복원하는지 측정하기 위한 **평가 노트북**이며, 실행 후 다음 세 질문에 답할 수 있어야 한다.

| # | 평가 영역 | 핵심 질문 |
|---|---|---|
| 1 | **Layout Analysis** | Text / Heading / Table / Picture / List / Header / Footer 영역을 올바른 문서 요소로 구분하는가? |
| 2 | **Text Hierarchy** | Heading → Subheading → Paragraph 계층과 문서 내 순서를 보존하는가? |
| 3 | **Table Structure** | 표의 Row / Column / Header / Cell / 병합 구조를 복원하는가? |

**대상 문서** — 사내 규정 `tiger_inc/pdf/*.pdf` 8종 + 법령 `tiger_inc/law/*.pdf` 3종, 총 11개 PDF를
한 번에 돌린다. 일부만 보려면 §2의 `TARGET_PDFS` 한 줄만 바꾼다.

**구성**

1. 환경 및 라이브러리 설정 → 2. PDF·경로 설정 → 3. Docling 문서 변환 → 4. Layout Analysis →
5. Text Hierarchy → 6. Table Structure → 7. 전체 결과 요약 → 8. Markdown 결과 저장

**실행 환경 주의 (이 머신 기준)**

- Docling은 base 파이썬이 아니라 conda env `docling`에 설치되어 있다
  (`C:\Users\young\miniconda3\envs\docling\python.exe` — docling 2.119.0 / Python 3.12).
  **반드시 해당 env의 커널로 실행**할 것.
- 실행 산출물은 전부 `docling_eval/output/` 아래에만 생성된다.
- 전체 11개 문서(222페이지) 변환은 CPU 기준 수 분~십수 분이 걸린다.

---
## 1. 환경 및 라이브러리 설정

`TORCHDYNAMO_DISABLE=1`을 **torch/docling import 이전에** 설정한다. 레이아웃 모델이 `torch.compile`을
쓰는데, MSVC(`cl.exe`)·triton이 없는 환경에서는 전 페이지가 `Compiler: cl is not found`로 실패해
변환 전체가 `status=failure`로 끝난다. import 뒤에 설정하면 효과가 없다.

In [1]:
import os

# ── torch / docling import 보다 반드시 먼저 (위 설명 참조) ──────────────────
os.environ.setdefault("TORCHDYNAMO_DISABLE", "1")

import json
import sys
import time
import traceback
from importlib.metadata import version as pkg_version
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display

from docling.backend.pypdfium2_backend import PyPdfiumDocumentBackend
from docling.datamodel.base_models import ConversionStatus, InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling_core.types.doc import ContentLayer, DocItemLabel
from docling_core.types.doc.document import ListItem, SectionHeaderItem, TableItem

pd.set_option("display.max_colwidth", 70)
pd.set_option("display.max_rows", 250)
pd.set_option("display.width", 200)

print(f"python       : {sys.version.split()[0]}")
print(f"executable   : {sys.executable}")
for _pkg in ("docling", "docling-core", "pandas"):
    print(f"{_pkg:13}: {pkg_version(_pkg)}")

python       : 3.12.13
executable   : c:\Users\young\miniconda3\envs\docling\python.exe
docling      : 2.119.0
docling-core : 2.91.0
pandas       : 3.0.5

---
## 2. PDF 파일 및 경로 설정

- `BASE_DIR`는 노트북을 **레포 루트에서 열든 `docling_eval/` 안에서 열든** 항상 같은
  `.../docling_eval` 하나를 가리킨다(`docling_eval/docling_eval` 중복 방지).
- **대상 문서를 바꾸려면 `TARGET_PDFS` 한 줄만 수정**한다. `None`이면 `tiger_inc/pdf`와
  `tiger_inc/law`의 모든 PDF를 대상으로 한다.
- PDF를 하나도 못 찾으면 어디를 뒤졌는지 함께 담아 `FileNotFoundError`를 낸다.

In [2]:
def _resolve_base_dir() -> Path:
    """CWD가 레포 루트든 docling_eval 내부든 같은 docling_eval 을 가리키게 한다."""
    cwd = Path.cwd().resolve()
    for cand in (cwd, *cwd.parents):
        if cand.name == "docling_eval":
            return cand
        if (cand / "docling_eval").is_dir() or (cand / "tiger_inc").is_dir():
            return cand / "docling_eval"
    return cwd / "docling_eval"


BASE_DIR = _resolve_base_dir()
REPO_ROOT = BASE_DIR.parent

OUTPUT_DIR = BASE_DIR / "output"
LAYOUT_DIR = OUTPUT_DIR / "layout"
HIER_DIR = OUTPUT_DIR / "hierarchy"
TABLE_DIR = OUTPUT_DIR / "tables"
MD_DIR = OUTPUT_DIR / "markdown"
for _d in (OUTPUT_DIR, LAYOUT_DIR, HIER_DIR, TABLE_DIR, MD_DIR):
    _d.mkdir(parents=True, exist_ok=True)

# ▼▼▼ 검증 대상 — 바꿀 곳은 여기뿐 ▼▼▼
PDF_DIRS = [REPO_ROOT / "tiger_inc" / "pdf", REPO_ROOT / "tiger_inc" / "law"]
TARGET_PDFS = None      # None = 위 폴더의 전체 PDF. 일부만: ["법인카드_사용규정", "법인세법"]
# ▲▲▲

PDF_PATHS = []
for _dir in PDF_DIRS:
    if not _dir.is_dir():
        print(f"[warn] 폴더가 없습니다: {_dir}")
        continue
    for _p in sorted(_dir.glob("*.pdf")):
        if TARGET_PDFS is None or _p.stem in TARGET_PDFS:
            PDF_PATHS.append(_p)

if not PDF_PATHS:
    raise FileNotFoundError(
        "대상 PDF를 찾지 못했습니다.\n"
        + "".join(f"  탐색: {d}\n" for d in PDF_DIRS)
        + f"  TARGET_PDFS = {TARGET_PDFS}\n"
        "→ 위 셀의 PDF_DIRS / TARGET_PDFS 를 확인하세요."
    )

print(f"BASE_DIR   : {BASE_DIR}")
print(f"OUTPUT_DIR : {OUTPUT_DIR}")
print(f"대상 PDF   : {len(PDF_PATHS)}개\n")

target_df = pd.DataFrame(
    [
        {
            "Document": p.stem,
            "Folder": p.parent.name,
            "Size (KB)": round(p.stat().st_size / 1024, 1),
            "Path": p.relative_to(REPO_ROOT).as_posix(),
        }
        for p in PDF_PATHS
    ]
)
display(target_df)

BASE_DIR   : D:\project\SKN29-FINAL-1TEAM\docling_eval
OUTPUT_DIR : D:\project\SKN29-FINAL-1TEAM\docling_eval\output
대상 PDF   : 11개

      Document Folder  Size (KB)                          Path
0    법인카드_사용규정    pdf      612.5   tiger_inc/pdf/법인카드_사용규정.pdf
1         부서소개    pdf      298.7        tiger_inc/pdf/부서소개.pdf
2   업무추진비_사용규정    pdf      598.1  tiger_inc/pdf/업무추진비_사용규정.pdf
3          조직도    pdf      706.4         tiger_inc/pdf/조직도.pdf
4   조직설계_상세기획서    pdf      782.5  tiger_inc/pdf/조직설계_상세기획서.pdf
5         직급체계    pdf      517.6        tiger_inc/pdf/직급체계.pdf
6     출장비_사용규정    pdf      585.2    tiger_inc/pdf/출장비_사용규정.pdf
7      회식_운영규정    pdf      637.1     tiger_inc/pdf/회식_운영규정.pdf
8         법인세법    law      570.3        tiger_inc/law/법인세법.pdf
9       부가가치세법    law      269.5      tiger_inc/law/부가가치세법.pdf
10    여신전문금융업법    law      268.5    tiger_inc/law/여신전문금융업법.pdf

---
## 3. Docling 문서 변환

파이프라인 옵션 세 가지가 이 평가의 전제다.

- `do_table_structure=True` + `do_cell_matching=True` — 표를 텍스트가 아니라 **셀 격자**로 복원한다(§6에서 검증).
- `heading_hierarchy_options.enabled=True` — **기본값이 `False`**이고, 그 상태에서는 모든 `section_header`가
  `level=1`로 평탄화되어 계층 검증(§5)이 무의미해진다. 켜면 제N장 → H1, 제N조 → H2 구조가 살아난다.
- `do_ocr=False` — 대상이 전부 텍스트 PDF다. 스캔본이라면 `True`로.

백엔드는 `pypdfium2` → 기본 `docling-parse` 순으로 시도한다. 한글 PDF·한글 경로에서 기본 백엔드가
`'utf-8' codec can't decode byte ...` / `Failed to load document with key` 로 실패하는 사례가 있어
폴백을 둔다. 어느 백엔드가 쓰였는지는 결과 표의 `Backend` 열에 남는다.

> 11개 문서 전체 변환은 CPU에서 수 분~십수 분이 걸린다. 문서 하나가 실패해도 나머지는 계속 진행하고,
> 실패 사유는 `[FAIL]` 줄과 결과 표의 `Note`에 남는다.

In [3]:
pipeline_options = PdfPipelineOptions()
pipeline_options.do_table_structure = True
pipeline_options.table_structure_options.do_cell_matching = True
pipeline_options.do_ocr = False                              # 텍스트 PDF 기준
pipeline_options.heading_hierarchy_options.enabled = True    # ← 계층 검증(§5)의 핵심 스위치


def _build_converter(backend):
    fmt = PdfFormatOption(pipeline_options=pipeline_options)
    if backend is not None:
        fmt.backend = backend
    return DocumentConverter(format_options={InputFormat.PDF: fmt})


# 모델 로딩 비용을 아끼려 컨버터는 한 번만 만들어 전 문서에 재사용한다.
CONVERTERS = [
    ("pypdfium2", _build_converter(PyPdfiumDocumentBackend)),
    ("docling-parse (default)", _build_converter(None)),
]
OK_STATUS = (ConversionStatus.SUCCESS, ConversionStatus.PARTIAL_SUCCESS)

DOCS = {}          # 문서명 -> DoclingDocument
conv_rows = []

print("=" * 78)
print("Docling Document Conversion")
print("=" * 78)

for i, pdf in enumerate(PDF_PATHS, start=1):
    name = pdf.stem
    doc = backend_used = None
    status, n_errors, note = "FAILURE", 0, ""
    t0 = time.perf_counter()

    for label, converter in CONVERTERS:
        try:
            res = converter.convert(pdf)
        except Exception as exc:  # noqa: BLE001 — 백엔드별 예외를 모아 폴백한다
            note = f"{label}: {type(exc).__name__}: {exc}"[:160]
            continue
        if res.status in OK_STATUS:
            doc, backend_used = res.document, label
            status, n_errors = res.status.value.upper(), len(res.errors)
            break
        note = f"{label}: status={res.status.value}"

    elapsed = time.perf_counter() - t0
    row = {
        "Document": name, "Folder": pdf.parent.name, "Status": status,
        "Backend": backend_used or "-", "Pages": doc.num_pages() if doc else 0,
        "Texts": len(doc.texts) if doc else 0, "Tables": len(doc.tables) if doc else 0,
        "Pictures": len(doc.pictures) if doc else 0, "Groups": len(doc.groups) if doc else 0,
        "Errors": n_errors, "Sec": round(elapsed, 1), "Note": note,
    }
    conv_rows.append(row)

    if doc is None:
        print(f"[{i:2}/{len(PDF_PATHS)}] [FAIL] {name}  ← {note}")
    else:
        DOCS[name] = doc
        print(
            f"[{i:2}/{len(PDF_PATHS)}] {name:24.24s} pages={row['Pages']:3}  {status:15.15s}"
            f"  backend={backend_used:10.10s}  texts={row['Texts']:4}  tables={row['Tables']:3}"
            f"  pics={row['Pictures']:3}  {elapsed:6.1f}s"
        )

conversion_df = pd.DataFrame(conv_rows)
print(f"\n변환 성공 {len(DOCS)} / {len(PDF_PATHS)} 건")
if not DOCS:
    raise RuntimeError("모든 문서 변환이 실패했습니다. 위 [FAIL] 사유와 Note 열을 확인하세요.")
display(conversion_df)

==============================================================================
Docling Document Conversion
==============================================================================

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

[ 1/11] 법인카드_사용규정                pages=  7  SUCCESS          backend=pypdfium2   texts= 118  tables=  2  pics=  0     3.8s
[ 2/11] 부서소개                     pages=  5  SUCCESS          backend=pypdfium2   texts=  23  tables=  9  pics=  0     1.2s
[ 3/11] 업무추진비_사용규정               pages=  6  SUCCESS          backend=pypdfium2   texts=  99  tables=  2  pics=  0     0.5s
[ 4/11] 조직도                      pages=  6  SUCCESS          backend=pypdfium2   texts=  86  tables=  4  pics=  1     0.6s
[ 5/11] 조직설계_상세기획서               pages= 12  SUCCESS          backend=pypdfium2   texts= 137  tables= 12  pics=  1     2.0s
[ 6/11] 직급체계                     pages=  4  SUCCESS          backend=pypdfium2   texts=  28  tables=  3  pics=  0     0.6s
[ 7/11] 출장비_사용규정                 pages=  6  SUCCESS          backend=pypdfium2   texts=  79  tables=  4  pics=  0     0.6s
[ 8/11] 회식_운영규정                  pages= 10  SUCCESS          backend=pypdfium2   texts=  94  tables= 11  pics=  0     2.0s
[ 9/11] 법인세법                     pages= 97  SUCCESS          backend=pypdfium2   texts=2093  tables=  4  pics=  3     7.6s
[10/11] 부가가치세법                   pages= 35  SUCCESS          backend=pypdfium2   texts= 763  tables=  3  pics=  1     1.9s
[11/11] 여신전문금융업법                 pages= 34  SUCCESS          backend=pypdfium2   texts= 907  tables=  0  pics=  1     2.4s

변환 성공 11 / 11 건

      Document Folder   Status    Backend  Pages  Texts  Tables  Pictures  Groups  Errors  Sec Note
0    법인카드_사용규정    pdf  SUCCESS  pypdfium2      7    118       2         0      16       0  3.8
1         부서소개    pdf  SUCCESS  pypdfium2      5     23       9         0       0       0  1.2
2   업무추진비_사용규정    pdf  SUCCESS  pypdfium2      6     99       2         0      10       0  0.5
3          조직도    pdf  SUCCESS  pypdfium2      6     86       4         1       4       0  0.6
4   조직설계_상세기획서    pdf  SUCCESS  pypdfium2     12    137      12         1      13       0  2.0
5         직급체계    pdf  SUCCESS  pypdfium2      4     28       3         0       5       0  0.6
6     출장비_사용규정    pdf  SUCCESS  pypdfium2      6     79       4         0      10       0  0.6
7      회식_운영규정    pdf  SUCCESS  pypdfium2     10     94      11         0       5       0  2.0
8         법인세법    law  SUCCESS  pypdfium2     97   2093       4         3     258       0  7.6
9       부가가치세법    law  SUCCESS  pypdfium2     35    763       3         1      87       0  1.9
10    여신전문금융업법    law  SUCCESS  pypdfium2     34    907       0         1     122       0  2.4

---
## 4. Layout Analysis 검증

> **Docling이 PDF 페이지의 서로 다른 영역을 올바른 문서 요소로 구분하는가?**

`doc.iterate_items()`로 문서 트리를 리딩오더대로 순회하며 요소마다
**Page / Element Type / Bounding Box / Text / Order**를 뽑는다.

- 머리말·꼬리말(`page_header`/`page_footer`)은 docling이 `FURNITURE` 콘텐츠 레이어에 넣고
  기본 순회에서 **제외**한다. Header/Footer 인식률도 평가 대상이므로 `BODY ∪ FURNITURE`로 순회한다.
- docling 원본 라벨(30종)은 CSV의 `Docling Label`에 그대로 남기고, 화면 집계는
  Title/Heading/Text/List/Table/Picture/Caption/Header/Footer/… 로 묶어 본다.

결과는 `output/layout/layout_result.csv`(요소 단위 전수) 및 집계 CSV 2종으로 저장한다.

In [4]:
# docling 원본 라벨 → 화면 집계용 요소 타입
ELEMENT_GROUP = {
    "title": "Title", "section_header": "Heading",
    "text": "Text", "paragraph": "Text",
    "list_item": "List",
    "table": "Table", "document_index": "Table",
    "picture": "Picture", "chart": "Picture",
    "caption": "Caption", "footnote": "Footnote",
    "page_header": "Header", "page_footer": "Footer",
    "formula": "Formula", "code": "Code", "reference": "Reference",
    "form": "Form", "key_value_region": "Form",
}
# 머리말/꼬리말을 세려면 FURNITURE 를 포함해야 한다(기본 순회는 BODY 만).
INCLUDED_LAYERS = {ContentLayer.BODY, ContentLayer.FURNITURE}


def _element_text(item, doc) -> str:
    if isinstance(item, TableItem):
        return item.caption_text(doc) or f"<table {item.data.num_rows}x{item.data.num_cols}>"
    text = getattr(item, "text", None)
    if text:
        return " ".join(text.split())
    label = getattr(getattr(item, "label", None), "value", "item")
    return f"<{label}>"


def _heading_level(item, label: str) -> str:
    if isinstance(item, SectionHeaderItem):
        return f"H{item.level}"
    return "H1" if label == "title" else ""


def collect_elements(name: str, doc) -> list[dict]:
    rows = []
    items = doc.iterate_items(with_groups=False, included_content_layers=INCLUDED_LAYERS)
    for order, (item, depth) in enumerate(items, start=1):
        label = getattr(getattr(item, "label", None), "value", None)
        if label is None:       # 라벨 없는 컨테이너 노드는 건너뛴다
            continue
        prov = list(getattr(item, "prov", None) or [])
        bbox = prov[0].bbox if prov else None
        text = _element_text(item, doc)
        rows.append({
            "Document": name,
            "Order": order,
            "Page": prov[0].page_no if prov else None,
            "Element Type": ELEMENT_GROUP.get(label, "Other"),
            "Docling Label": label,
            "Level": _heading_level(item, label),
            "Depth": depth,
            "Marker": (getattr(item, "marker", "") or "") if isinstance(item, ListItem) else "",
            "BBox (l,t,r,b)": (
                f"{bbox.l:.1f},{bbox.t:.1f},{bbox.r:.1f},{bbox.b:.1f}" if bbox else ""
            ),
            "Chars": len(text),
            "Text": text,
        })
    return rows


layout_rows = []
for _name, _doc in DOCS.items():
    try:
        layout_rows.extend(collect_elements(_name, _doc))
    except Exception:  # noqa: BLE001 — 한 문서가 깨져도 나머지는 집계한다
        print(f"[error] Layout 수집 실패: {_name}")
        traceback.print_exc()

layout_df = pd.DataFrame(layout_rows)
layout_df.to_csv(LAYOUT_DIR / "layout_result.csv", index=False, encoding="utf-8-sig")
print(f"요소 {len(layout_df):,}개 수집 → {(LAYOUT_DIR / 'layout_result.csv').relative_to(BASE_DIR)}")

_unknown = sorted(set(layout_df.loc[layout_df["Element Type"] == "Other", "Docling Label"]))
if _unknown:
    print(f"[note] 매핑되지 않은 docling 라벨(Other 로 집계): {_unknown}")

display(layout_df.head(15))

요소 4,388개 수집 → output\layout\layout_result.csv

     Document  Order  Page Element Type   Docling Label Level  Depth Marker           BBox (l,t,r,b)  Chars                                                                   Text
0   법인카드_사용규정      1     1      Heading  section_header    H1      1         206.1,594.1,387.6,580.0     34                                     타 이 거 주 식 회 사 ( T i ge r I n c . )
1   법인카드_사용규정      2     1      Heading  section_header    H1      1         183.0,511.9,409.3,486.4     10                                                             법인카드 사용 규정
2   법인카드_사용규정      3     1        Table           table            1         205.0,378.9,389.8,292.6     11                                                            <table 3x2>
3   법인카드_사용규정      4     1         Text            text            1         113.3,272.4,481.4,251.2    100  개정이력 v1.0 제정 (조문 정합성 검토 반영) / v1.1 개정: 제2조 관리자 정의 정비, 제10조 사전승인 예외...
4   법인카드_사용규정      5     1         Text            text            1            91.5,95.7,503.8,63.4    212  ※ 본 규정은 데모/교육 목적의 가상 기업(타이거 주식회사, Tiger Inc.) 시나리오용으로 작성되었으며, 회사는 ...
5   법인카드_사용규정      6     2       Header     page_header            1         265.3,811.5,329.8,803.8     10                                                             법인카드 사용 규정
6   법인카드_사용규정      7     2      Heading  section_header    H2      1          62.6,666.8,120.8,654.9      8                                                               제1조 (목적)
7   법인카드_사용규정      8     2         Text            text            1          62.6,641.1,532.8,597.0    152  이 규정은 타이거 주식회사(이하 "회사")가 임직원에게 발급하는 법인카드의 발급, 관리, 사용 및 정산에 관 한 사항을...
8   법인카드_사용규정      9     2      Heading  section_header    H2      1          62.6,572.0,160.4,560.1     16                                                       제2조 (정의) 개정 v1.1
9   법인카드_사용규정     10     2         Text            text            1          63.4,546.4,279.5,536.3     27                                            이 규정에서 사용하는 용어의 정의는 다음과 같다.
10  법인카드_사용규정     11     2         List       list_item            2     1.   63.0,529.7,532.8,503.0     57              "법인카드"란 회사 명의로 발급되어 임직원이 업무 목적의 지출에 사용하는 신용카드·체크카드를 말한 다.
11  법인카드_사용규정     12     2         List       list_item            2     2.   63.0,496.4,337.6,486.2     32                                       "사용자"란 법인카드를 발급받아 사용하는 임직원을 말한다.
12  법인카드_사용규정     13     2         List       list_item            2     3.   62.6,479.7,532.7,435.1    129  "관리자"란 법인카드 정산 승인 권한을 가진 자로서 「직급체계」에 따라 결재권을 보유한 팀장·부서장· 본부장 및 대표이...
13  법인카드_사용규정     14     2         List       list_item            2     4.   62.7,429.6,532.7,368.4    186  "담당자"란 법인카드를 발급받아 사용하고 정산을 신청하는 임직원 본인을 말하며, 법인카드 사용 신청· 영수증 업로드·사...
14  법인카드_사용규정     15     2         List       list_item            2     5.   62.8,362.9,532.7,335.0     65      "기업업무추진비"란 회사가 업무와 관련하여 접대·교제·사례 등의 목적으로 지출하는 비용을 말한다(종 전 "접대비").

### 4-1. 요소 타입 집계 — 문서별 / 전체 / 페이지별

In [5]:
# (a) 문서 × 요소 타입
layout_by_document = (
    pd.crosstab(layout_df["Document"], layout_df["Element Type"], margins=True, margins_name="ALL")
    .sort_index()
)
layout_by_document.to_csv(LAYOUT_DIR / "layout_by_document.csv", encoding="utf-8-sig")
print("[a] 문서별 요소 타입 집계")
display(layout_by_document)

# (b) 전체 요소 타입
layout_totals = (
    layout_df["Element Type"].value_counts().rename_axis("Element Type").reset_index(name="Count")
)
layout_totals["Ratio"] = (layout_totals["Count"] / len(layout_df)).round(3)
print("[b] 전체 문서 요소 타입 합계")
display(layout_totals)

# (c) 페이지별 (전 문서 전수 저장 + 한 문서 미리보기)
layout_by_page = (
    layout_df.groupby(["Document", "Page", "Element Type"], dropna=False)
    .size().reset_index(name="Count")
)
layout_by_page.to_csv(LAYOUT_DIR / "layout_by_page.csv", index=False, encoding="utf-8-sig")

PREVIEW_DOC = next(iter(DOCS))          # 미리보기 문서 — 바꿔가며 확인 가능
_prev = layout_df[layout_df["Document"] == PREVIEW_DOC]
print(f"[c] 페이지별 요소 타입 — 미리보기: {PREVIEW_DOC} (전 문서는 layout_by_page.csv)")
display(pd.crosstab(_prev["Page"], _prev["Element Type"], margins=True, margins_name="ALL"))

[a] 문서별 요소 타입 집계

Element Type  Caption  Code  Footer  Formula  Header  Heading  List  Picture  Table  Text   ALL
Document
ALL                 2    14     431        3     214      493  2432        7     54   738  4388
법인세법                0     6     194        3      97      188  1216        3      4   387  2098
법인카드_사용규정           1     0      12        0       6       28    60        0      2    11   120
부가가치세법              0     3      70        0      35       57   493        1      3   105   767
부서소개                0     0       9        0       4        9     0        0      9     1    32
업무추진비_사용규정          0     0      10        0       5       25    41        0      2    18   101
여신전문금융업법            0     5      68        0      34      103   530        1      0   167   908
조직도                 1     0      10        0       5        9     9        1      4     3    42
조직설계_상세기획서          0     0      22        0      11       23    25        1     12     7   101
직급체계                0     0       7        0       3        6     9        0      3     3    31
출장비_사용규정            0     0      10        0       5       24    28        0      4    12    83
회식_운영규정             0     0      19        0       9       21    21        0     11    24   105

[b] 전체 문서 요소 타입 합계

  Element Type  Count  Ratio
0         List   2432  0.554
1         Text    738  0.168
2      Heading    493  0.112
3       Footer    431  0.098
4       Header    214  0.049
5        Table     54  0.012
6         Code     14  0.003
7      Picture      7  0.002
8      Formula      3  0.001
9      Caption      2  0.000

[c] 페이지별 요소 타입 — 미리보기: 법인카드_사용규정 (전 문서는 layout_by_page.csv)

Element Type  Caption  Footer  Header  Heading  List  Table  Text  ALL
Page
1                   0       0       0        2     0      1     2    5
2                   0       2       1        4     6      0     3   16
3                   0       2       1        7    11      0     4   25
4                   0       2       1        4    16      0     0   23
5                   0       2       1        5    13      0     1   22
6                   0       2       1        6     9      0     1   19
7                   1       2       1        0     5      1     0   10
ALL                 1      12       6       28    60      2    11  120

---
## 5. Text Hierarchy 검증

> **Heading → Subheading → Paragraph 계층과 문서 내 순서를 보존하는가?**

`SectionHeaderItem.level`(§3에서 `heading_hierarchy_options`를 켜서 살아난 값)을 스택으로 삼아
본문·목록·표를 직전 헤딩 아래에 붙여 트리를 그린다. 화면에는 헤딩당 본문 3개까지만 접어서
보여주고, **접지 않은 전체 트리는 `output/hierarchy/<문서>_tree.txt`** 에 저장한다.

계층 품질은 눈으로만 보지 않고 세 지표로 함께 잰다.

| 지표 | 의미 | 나쁠 때 |
|---|---|---|
| `Level Jumps` | H1 → H3 처럼 레벨을 건너뛴 횟수 | 중간 헤딩을 본문으로 오인 |
| `Orphan Body` | 첫 헤딩보다 앞에 나온 본문 요소 수 | 표지·머리말이 본문에 섞임 (일부는 정상) |
| `Flat?` | 헤딩이 전부 H1인가 | 계층이 평탄화됨 (= 사실상 계층 복원 실패) |

In [6]:
HEADING_TYPES = {"Title", "Heading"}
BODY_TYPES = {"Text", "List", "Table", "Picture", "Caption", "Formula", "Code", "Footnote"}
TREE_TAG = {
    "Text": "TEXT", "List": "LIST", "Table": "TABLE", "Picture": "PIC",
    "Caption": "CAP", "Formula": "FORM", "Code": "CODE", "Footnote": "NOTE",
}

hierarchy_df = (
    layout_df[layout_df["Element Type"].isin(HEADING_TYPES | BODY_TYPES)]
    [["Document", "Order", "Page", "Element Type", "Level", "Marker", "Text"]]
    .rename(columns={"Element Type": "Type"})
    .reset_index(drop=True)
)
hierarchy_df.to_csv(HIER_DIR / "hierarchy_result.csv", index=False, encoding="utf-8-sig")


def render_tree(doc_name: str, max_body_per_heading: int = 3, text_width: int = 62) -> list[str]:
    """헤딩 레벨을 스택 삼아 문서 계층을 텍스트 트리로 그린다."""
    lines, cur_depth, shown = [], 0, 0
    for r in hierarchy_df[hierarchy_df["Document"] == doc_name].to_dict("records"):
        text = r["Text"]
        if len(text) > text_width:
            text = text[:text_width] + "…"
        if r["Type"] in HEADING_TYPES:
            level = r["Level"]
            depth = max(int(level[1:]) - 1, 0) if level.startswith("H") else 0
            cur_depth, shown = depth + 1, 0
            lines.append(f"{'│   ' * depth}├─ [{level or 'H?'}] {text}   (p.{r['Page']})")
        else:
            shown += 1
            if shown > max_body_per_heading:
                if shown == max_body_per_heading + 1:
                    lines.append(f"{'│   ' * cur_depth}└─ … (이하 생략)")
                continue
            marker = f"{r['Marker']} " if r["Marker"] else ""
            lines.append(f"{'│   ' * cur_depth}├─ [{TREE_TAG.get(r['Type'], r['Type'])}] {marker}{text}")
    return lines


def hierarchy_metrics(doc_name: str) -> dict:
    rows = hierarchy_df[hierarchy_df["Document"] == doc_name].to_dict("records")
    levels, jumps, orphan, seen_heading = [], 0, 0, False
    prev = 0
    for r in rows:
        if r["Type"] in HEADING_TYPES and r["Level"].startswith("H"):
            lvl = int(r["Level"][1:])
            levels.append(lvl)
            if prev and lvl > prev + 1:
                jumps += 1
            prev, seen_heading = lvl, True
        elif not seen_heading:
            orphan += 1
    return {
        "Document": doc_name,
        "Headings": len(levels),
        "Max Level": max(levels) if levels else 0,
        "Level Jumps": jumps,
        "Orphan Body": orphan,
        "Flat?": "YES (계층 없음)" if levels and max(levels) == 1 else "no",
    }


# 헤딩 레벨 분포 + 계층 품질 지표
_head = hierarchy_df[hierarchy_df["Type"].isin(HEADING_TYPES) & hierarchy_df["Level"].ne("")]
heading_level_df = pd.crosstab(_head["Document"], _head["Level"], margins=True, margins_name="ALL")
hierarchy_metrics_df = pd.DataFrame([hierarchy_metrics(n) for n in DOCS])

print("[a] 문서별 Heading 레벨 분포")
display(heading_level_df)
print("[b] 계층 품질 지표")
display(hierarchy_metrics_df)

# 전체 트리는 파일로, 화면에는 미리보기 문서만
for _name in DOCS:
    (HIER_DIR / f"{_name}_tree.txt").write_text(
        "\n".join(render_tree(_name, max_body_per_heading=10**9)), encoding="utf-8"
    )
print(f"\n전체 계층 트리 {len(DOCS)}건 저장 → {HIER_DIR.relative_to(BASE_DIR)}/<문서>_tree.txt")

[a] 문서별 Heading 레벨 분포

Level        H1   H2  ALL
Document
법인세법         35  153  188
법인카드_사용규정     9   19   28
부가가치세법       10   47   57
부서소개          9    0    9
업무추진비_사용규정    9   16   25
여신전문금융업법     11   92  103
조직도           9    0    9
조직설계_상세기획서   21    2   23
직급체계          6    0    6
출장비_사용규정      9   15   24
회식_운영규정      10   11   21
ALL         138  355  493

[b] 계층 품질 지표

      Document  Headings  Max Level  Level Jumps  Orphan Body        Flat?
0    법인카드_사용규정        28          2            0            0           no
1         부서소개         9          1            0            0  YES (계층 없음)
2   업무추진비_사용규정        25          2            0            0           no
3          조직도         9          1            0            0  YES (계층 없음)
4   조직설계_상세기획서        23          2            0            1           no
5         직급체계         6          1            0            0  YES (계층 없음)
6     출장비_사용규정        24          2            0            0           no
7      회식_운영규정        21          2            0            0           no
8         법인세법       188          2            0            0           no
9       부가가치세법        57          2            0            0           no
10    여신전문금융업법       103          2            0            0           no

전체 계층 트리 11건 저장 → output\hierarchy/<문서>_tree.txt

In [7]:
# 미리보기 트리 — PREVIEW_DOC 를 바꾸면 다른 문서를 볼 수 있다
TREE_PREVIEW_LINES = 45

print("=" * 78)
print(f"DOCUMENT HIERARCHY — {PREVIEW_DOC}")
print("=" * 78)
_lines = render_tree(PREVIEW_DOC)
for _line in _lines[:TREE_PREVIEW_LINES]:
    print(_line)
if len(_lines) > TREE_PREVIEW_LINES:
    print(f"... ({len(_lines) - TREE_PREVIEW_LINES}줄 더 — 전체는 hierarchy/{PREVIEW_DOC}_tree.txt)")

print("\n[요소 순서 표 — 앞 20행]")
display(hierarchy_df[hierarchy_df["Document"] == PREVIEW_DOC].head(20))

==============================================================================
DOCUMENT HIERARCHY — 법인카드_사용규정
==============================================================================
├─ [H1] 타 이 거 주 식 회 사 ( T i ge r I n c . )   (p.1)
├─ [H1] 법인카드 사용 규정   (p.1)
│   ├─ [TABLE] <table 3x2>
│   ├─ [TEXT] 개정이력 v1.0 제정 (조문 정합성 검토 반영) / v1.1 개정: 제2조 관리자 정의 정비, 제10조 사전승…
│   ├─ [TEXT] ※ 본 규정은 데모/교육 목적의 가상 기업(타이거 주식회사, Tiger Inc.) 시나리오용으로 작성되었으며, …
│   ├─ [H2] 제1조 (목적)   (p.2)
│   │   ├─ [TEXT] 이 규정은 타이거 주식회사(이하 "회사")가 임직원에게 발급하는 법인카드의 발급, 관리, 사용 및 정산에 관 한…
│   ├─ [H2] 제2조 (정의) 개정 v1.1   (p.2)
│   │   ├─ [TEXT] 이 규정에서 사용하는 용어의 정의는 다음과 같다.
│   │   ├─ [LIST] 1. "법인카드"란 회사 명의로 발급되어 임직원이 업무 목적의 지출에 사용하는 신용카드·체크카드를 말한 다.
│   │   ├─ [LIST] 2. "사용자"란 법인카드를 발급받아 사용하는 임직원을 말한다.
│   │   └─ … (이하 생략)
│   ├─ [H2] 제3조 (적용범위)   (p.2)
│   │   ├─ [TEXT] 이 규정은 회사로부터 법인카드를 발급받은 모든 임직원에게 적용한다.
├─ [H1] 제1장 총칙   (p.2)
│   ├─ [H2] 제4조 (발급 대상)   (p.3)
│   │   ├─ [LIST] 팀장 이상 직책(팀장·부서장·본부장·대표이사)을 보임한 임직원에게는 원칙적으로 개인 법인카드를 발 급한다. 1.
│   │   ├─ [LIST] 직책이 없는 임직원(비직책자)은 부서 공용카드를 사용하거나, 업무상 필요가 인정되는 경우 관리자 승 2.
│   │   ├─ [LIST] 인을 받아 개인 카드를 발급받을 수 있다.
│   ├─ [H2] 제5조 (발급 절차)   (p.3)
│   │   ├─ [TEXT] 사용자는 소속 부서장의 승인을 받아 「법인카드 발급 신청서」를 경영지원본부에 제출하며, 경영지원본부 는 신청 내…
│   ├─ [H2] 제6조 (관리 책임)   (p.3)
│   │   ├─ [LIST] 사용자는 법인카드를 선량한 관리자의 주의로 보관·사용하여야 하며, 타인에게 양도·대여할 수 없다. 다 만 제4조…
│   │   ├─ [LIST] 퇴사, 휴직, 부서 이동 시 사용자는 지체 없이 법인카드를 반납하여야 한다. 2.
│   ├─ [H2] 제7조 (분실·도난 시 조치)   (p.3)
│   │   ├─ [TEXT] 사용자는 법인카드의 분실 또는 도난을 인지한 즉시 카드사에 사용정지를 요청하고, 24시간 이내에 경영지
│   │   ├─ [TEXT] 원본부에 서면(이메일 포함)으로 보고하여야 한다.
├─ [H1] 제3장 법인카드 사용 원칙   (p.3)
│   ├─ [H2] 제8조 (사용 가능 항목)   (p.3)
│   │   ├─ [TEXT] 법인카드는 다음 각 호의 업무 목적 지출에 한하여 사용할 수 있다.
│   │   ├─ [LIST] 1. 거래처 미팅, 회의 관련 식대 및 다과비
│   │   ├─ [LIST] 2. 기업업무추진비(거래처 접대, 경조사비 등 업무 관련성이 인정되는 지출)
│   │   └─ … (이하 생략)
├─ [H1] 제2장 법인카드의 발급 및 관리   (p.3)
│   ├─ [H2] 제9조 (사용 제한 및 금지 항목)   (p.4)
│   │   ├─ [LIST] 사적 용도의 지출 1.
│   │   ├─ [LIST] 유흥업소, 사행성 업종에서의 지출 2.
│   │   ├─ [LIST] 상품권 등 유가증권의 현금 구매(부득이 상품권을 구입하는 경우 반드시 신용카드로 결제하여 적격증빙 을 확보한다)…
│   │   └─ … (이하 생략)
│   ├─ [H2] 제10조 (사용 한도) 개정 v1.1   (p.4)
│   │   ├─ [LIST] 1일 사용한도 및 월 사용한도는 직책별로 별표 1과 같이 정한다. 1.
│   │   ├─ [LIST] 건당 지출에 대한 사전승인 기준은 원칙적으로 직책별로 별표 1과 같이 정한다. 다만, 식대·기업업무추 진비 지출…
│   │   ├─ [LIST] 부득이한 사유로 제1항·제2항의 사전승인 기준을 초과하는 지출에 대해 사전승인을 받지 못한 경우, 사 용자는 정…
├─ [H1] 제4장 증빙 및 정산   (p.4)
│   ├─ [H2] 제11조 (증빙서류의 원칙)   (p.4)
... (36줄 더 — 전체는 hierarchy/법인카드_사용규정_tree.txt)

[요소 순서 표 — 앞 20행]

     Document  Order  Page     Type Level Marker                                                                   Text
0   법인카드_사용규정      1     1  Heading    H1                                            타 이 거 주 식 회 사 ( T i ge r I n c . )
1   법인카드_사용규정      2     1  Heading    H1                                                                    법인카드 사용 규정
2   법인카드_사용규정      3     1    Table                                                                         <table 3x2>
3   법인카드_사용규정      4     1     Text               개정이력 v1.0 제정 (조문 정합성 검토 반영) / v1.1 개정: 제2조 관리자 정의 정비, 제10조 사전승인 예외...
4   법인카드_사용규정      5     1     Text               ※ 본 규정은 데모/교육 목적의 가상 기업(타이거 주식회사, Tiger Inc.) 시나리오용으로 작성되었으며, 회사는 ...
5   법인카드_사용규정      7     2  Heading    H2                                                                      제1조 (목적)
6   법인카드_사용규정      8     2     Text               이 규정은 타이거 주식회사(이하 "회사")가 임직원에게 발급하는 법인카드의 발급, 관리, 사용 및 정산에 관 한 사항을...
7   법인카드_사용규정      9     2  Heading    H2                                                              제2조 (정의) 개정 v1.1
8   법인카드_사용규정     10     2     Text                                                         이 규정에서 사용하는 용어의 정의는 다음과 같다.
9   법인카드_사용규정     11     2     List           1.              "법인카드"란 회사 명의로 발급되어 임직원이 업무 목적의 지출에 사용하는 신용카드·체크카드를 말한 다.
10  법인카드_사용규정     12     2     List           2.                                       "사용자"란 법인카드를 발급받아 사용하는 임직원을 말한다.
11  법인카드_사용규정     13     2     List           3.  "관리자"란 법인카드 정산 승인 권한을 가진 자로서 「직급체계」에 따라 결재권을 보유한 팀장·부서장· 본부장 및 대표이...
12  법인카드_사용규정     14     2     List           4.  "담당자"란 법인카드를 발급받아 사용하고 정산을 신청하는 임직원 본인을 말하며, 법인카드 사용 신청· 영수증 업로드·사...
13  법인카드_사용규정     15     2     List           5.      "기업업무추진비"란 회사가 업무와 관련하여 접대·교제·사례 등의 목적으로 지출하는 비용을 말한다(종 전 "접대비").
14  법인카드_사용규정     16     2     List           6.            "적격증명서류"란 신용카드매출전표, 현금영수증, 세금계산서, 계산서 등 세법상 인정되는 증빙서류를 말한다.
15  법인카드_사용규정     17     2  Heading    H2                                                                    제3조 (적용범위)
16  법인카드_사용규정     18     2     Text                                               이 규정은 회사로부터 법인카드를 발급받은 모든 임직원에게 적용한다.
17  법인카드_사용규정     19     2  Heading    H1                                                                        제1장 총칙
18  법인카드_사용규정     23     3  Heading    H2                                                                   제4조 (발급 대상)
19  법인카드_사용규정     24     3     List                      팀장 이상 직책(팀장·부서장·본부장·대표이사)을 보임한 임직원에게는 원칙적으로 개인 법인카드를 발 급한다. 1.

---
## 6. Table Structure 검증

> **원본 PDF의 표가 텍스트 덩어리가 아니라 행/열/셀 구조로 얼마나 정확하게 복원되는가?**

`TableItem.data`(= `TableData`)의 셀 목록을 직접 뜯어 다음을 센다.

- `num_rows` / `num_cols` / 셀 수
- `column_header=True` 셀 → **헤더 검출 여부**, 헤더가 걸친 **행 수 → 다중 헤더**
- `row_header=True` 셀 → 좌측 헤더(레이블 열)
- `row_span>1 or col_span>1` → **병합 셀**
- 빈 셀 수와 채움률(`Fill Rate`) — 셀 매칭이 실패하면 여기서 먼저 티가 난다

표마다 `output/tables/<문서>/table_NN.csv`(DataFrame)와 `table_NN.json`(셀 단위 구조 + Markdown)을
남긴다. 화면에는 문서당 `TABLE_DETAIL_LIMIT`개만 상세 출력한다(저장은 전부).

> **`Rows=0, Cols=0`인 표를 특히 눈여겨볼 것.** docling이 "여기 표가 있다"는 영역은 잡았는데 셀 격자
> 복원에는 실패한 경우다. 표 개수만 세면 성공처럼 보이지만 실제로는 내용이 통째로 비어 있다.
> `Note` 열에 `표 영역만 검출 · 셀 구조 복원 실패 (0x0)`로 표시된다.

In [8]:
TABLE_DETAIL_LIMIT = 2      # 문서당 화면에 상세 출력할 표 수 (파일 저장은 전부)
TABLE_MD_LINES = 12         # 화면에 보여줄 Markdown 표의 최대 줄 수


def table_structure(name: str, doc, idx: int, table) -> dict:
    data = table.data
    cells = list(data.table_cells or [])
    header_cells = [c for c in cells if c.column_header]
    row_header_cells = [c for c in cells if c.row_header]
    merged = [c for c in cells if (c.row_span or 1) > 1 or (c.col_span or 1) > 1]
    empty = [c for c in cells if not (c.text or "").strip()]
    header_rows = sorted({c.start_row_offset_idx for c in header_cells})
    prov = list(table.prov or [])
    return {
        "Document": name, "Table": idx,
        "Page": prov[0].page_no if prov else None,
        "Rows": data.num_rows, "Cols": data.num_cols, "Cells": len(cells),
        "Header": "Detected" if header_cells else "Not detected",
        "Header Rows": len(header_rows),
        "Multi Header": "Y" if len(header_rows) > 1 else "N",
        "Row Header": "Y" if row_header_cells else "N",
        "Merged Cells": len(merged),
        "Empty Cells": len(empty),
        "Fill Rate": round(1 - len(empty) / len(cells), 3) if cells else 0.0,
        "Caption": (table.caption_text(doc) or "")[:60],
        # 표 영역은 잡았는데 셀이 0개 = 구조 복원 실패. 그냥 두면 Rows/Cols 0 이 조용히 묻힌다.
        "Note": "" if cells else "표 영역만 검출 · 셀 구조 복원 실패 (0x0)",
    }


table_rows, table_frames = [], {}

for name, doc in DOCS.items():
    if not doc.tables:
        continue
    out_dir = TABLE_DIR / name
    out_dir.mkdir(parents=True, exist_ok=True)

    for idx, table in enumerate(doc.tables, start=1):
        info = table_structure(name, doc, idx, table)
        stem = out_dir / f"table_{idx:02d}"

        try:
            df = table.export_to_dataframe(doc)
            df.to_csv(stem.with_suffix(".csv"), index=False, encoding="utf-8-sig")
            table_frames[(name, idx)] = df
        except Exception as exc:  # noqa: BLE001 — 표 하나가 깨져도 나머지는 진행
            info["Note"] = f"DataFrame 변환 실패: {type(exc).__name__}: {exc}"[:120]

        try:
            markdown_table = table.export_to_markdown(doc)
        except Exception as exc:  # noqa: BLE001
            markdown_table = ""
            info["Note"] = (info["Note"] + f" | Markdown 실패: {type(exc).__name__}").strip(" |")

        payload = dict(info)
        payload["cells"] = [
            {
                "row": c.start_row_offset_idx, "col": c.start_col_offset_idx,
                "row_span": c.row_span, "col_span": c.col_span,
                "column_header": c.column_header, "row_header": c.row_header,
                "text": c.text,
            }
            for c in (table.data.table_cells or [])
        ]
        payload["markdown"] = markdown_table
        stem.with_suffix(".json").write_text(
            json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
        )

        table_rows.append(info)

tables_df = pd.DataFrame(table_rows)
if tables_df.empty:
    print("[note] 어떤 문서에서도 표가 검출되지 않았습니다.")
else:
    tables_df.to_csv(TABLE_DIR / "table_summary.csv", index=False, encoding="utf-8-sig")
    print(f"표 {len(tables_df)}개 → {TABLE_DIR.relative_to(BASE_DIR)}/<문서>/table_NN.[csv|json]")
    display(tables_df)

표 54개 → output\tables/<문서>/table_NN.[csv|json]

      Document  Table  Page  Rows  Cols  Cells        Header  Header Rows Multi Header Row Header  Merged Cells  Empty Cells  Fill Rate                       Caption                         Note
0    법인카드_사용규정      1     1     3     2      6  Not detected            0            N          N             0            0        1.0
1    법인카드_사용규정      2     7     6     4     24      Detected            1            N          N             0            0        1.0  별표 1. 직책별 법인카드 사용 한도 개정 v1.1
2         부서소개      1     2     6     5     30      Detected            1            N          N             0            0        1.0
3         부서소개      2     2     3     5     15      Detected            1            N          N             0            0        1.0
4         부서소개      3     3     3     5     15      Detected            1            N          N             0            0        1.0
5         부서소개      4     3     4     5     20      Detected            1            N          N             0            0        1.0
6         부서소개      5     3     3     5     15      Detected            1            N          N             0            0        1.0
7         부서소개      6     4     2     5     10      Detected            1            N          N             0            0        1.0
8         부서소개      7     4     2     5     10      Detected            1            N          N             0            0        1.0
9         부서소개      8     4     7     3     19      Detected            1            N          N             2            0        1.0
10        부서소개      9     5     6     3     18      Detected            1            N          N             0            0        1.0
11  업무추진비_사용규정      1     6     4     3     12      Detected            1            N          N             0            0        1.0
12  업무추진비_사용규정      2     6     5     2     10      Detected            1            N          N             0            0        1.0
13         조직도      1     2     8     2     16      Detected            1            N          N             0            0        1.0                      1. 회사 개요
14         조직도      2     4     2     2      4      Detected            1            N          N             0            0        1.0
15         조직도      3     5     4     2      8      Detected            1            N          N             0            0        1.0
16         조직도      4     6     4     2      8      Detected            1            N          N             0            0        1.0
17  조직설계_상세기획서      1     2     9     2     18      Detected            1            N          N             0            0        1.0
18  조직설계_상세기획서      2     5    11     5     55      Detected            1            N          N             0            0        1.0
19  조직설계_상세기획서      3     6     7     5     35      Detected            1            N          N             0            0        1.0
20  조직설계_상세기획서      4     7     4     4     14      Detected            1            N          N             1            0        1.0
21  조직설계_상세기획서      5     8     4     4     16      Detected            1            N          N             0            0        1.0
22  조직설계_상세기획서      6     9     5     4     20      Detected            1            N          N             0            0        1.0
23  조직설계_상세기획서      7     9     5     3     15      Detected            1            N          N             0            0        1.0
24  조직설계_상세기획서      8     9     3     3      8      Detected            1            N          N             1            0        1.0
25  조직설계_상세기획서      9    10     5     3     14      Detected            1            N          N             1            0        1.0
26  조직설계_상세기획서     10    11     6     3     18      Detected            1            N          N             0            0        1.0
27  조직설계_상세기획서     11    11     5     2     10      Detected            1            N          N             0            0        1.0
28  조직설계_상세기획서     12    12     4     2      8      Detected            1            N          N             0            0        1.0
29        직급체계      1     2     7     4     26      Detected            1            N          N             1            0        1.0
30        직급체계      2     3     5     4     20      Detected            1            N          N             0            0        1.0
31        직급체계      3     3     5     3     15      Detected            1            N          N             0            0        1.0
32    출장비_사용규정      1     1     3     2      6  Not detected            0            N          N             0            0        1.0
33    출장비_사용규정      2     5     3     4     12      Detected            1            N          N             0            0        1.0
34    출장비_사용규정      3     5     3     5     15      Detected            1            N          N             0            0        1.0
35    출장비_사용규정      4     6     2     5     10      Detected            1            N          N             0            0        1.0
36     회식_운영규정      1     2     9     3     25      Detected            1            N          N             2            0        1.0
37     회식_운영규정      2     3     5     5     25      Detected            1            N          N             0            0        1.0
38     회식_운영규정      3     4     3     2      6      Detected            1            N          N             0            0        1.0
39     회식_운영규정      4     5     5     4     20      Detected            1            N          N             0            0        1.0
40     회식_운영규정      5     6     6     3     18      Detected            1            N          N             0            0        1.0
41     회식_운영규정      6     7     3     3      9      Detected            1            N          N             0            0        1.0
42     회식_운영규정      7     7     6     2     12      Detected            1            N          N             0            0        1.0
43     회식_운영규정      8     8     5     5     25      Detected            1            N          N             0            0        1.0
44     회식_운영규정      9     9     6     5     30      Detected            1            N          N             0            0        1.0
45     회식_운영규정     10     9     2     7     14      Detected            1            N          Y             0            0        1.0
46     회식_운영규정     11    10     6     7     42      Detected            1            N          N             0            0        1.0
47        법인세법      1    14     0     0      0  Not detected            0            N          N             0            0        0.0                                표 영역만 검출 · 셀 구조 복원 실패 (0x0)
48        법인세법      2    20     0     0      0  Not detected            0            N          N             0            0        0.0                                표 영역만 검출 · 셀 구조 복원 실패 (0x0)
49        법인세법      3    39     0     0      0  Not detected            0            N          N             0            0        0.0                                표 영역만 검출 · 셀 구조 복원 실패 (0x0)
50        법인세법      4    39     0     0      0  Not detected            0            N          N             0            0        0.0                                표 영역만 검출 · 셀 구조 복원 실패 (0x0)
51      부가가치세법      1     5     0     0      0  Not detected            0            N          N             0            0        0.0                                표 영역만 검출 · 셀 구조 복원 실패 (0x0)
52      부가가치세법      2    19     0     0      0  Not detected            0            N          N             0            0        0.0                                표 영역만 검출 · 셀 구조 복원 실패 (0x0)
53      부가가치세법      3    21     0     0      0  Not detected            0            N          N             0            0        0.0                                표 영역만 검출 · 셀 구조 복원 실패 (0x0)

In [9]:
# 표 상세 — 문서당 TABLE_DETAIL_LIMIT 개
for name, doc in DOCS.items():
    for idx, table in enumerate(doc.tables[:TABLE_DETAIL_LIMIT], start=1):
        info = table_structure(name, doc, idx, table)
        print("=" * 78)
        print(f"TABLE {idx} — {name}")
        print("=" * 78)
        print(f"Page        : {info['Page']}")
        print(f"Rows        : {info['Rows']}")
        print(f"Columns     : {info['Cols']}")
        print(f"Header      : {info['Header']} (header rows={info['Header Rows']}, "
              f"multi={info['Multi Header']}, row-header={info['Row Header']})")
        print(f"Merged Cell : {'Detected (%d)' % info['Merged Cells'] if info['Merged Cells'] else 'None'}")
        print(f"Empty Cell  : {info['Empty Cells']}  (fill rate {info['Fill Rate']:.1%})")
        if info["Caption"]:
            print(f"Caption     : {info['Caption']}")
        if info["Note"]:
            print(f"Note        : {info['Note']}")

        df = table_frames.get((name, idx))
        if df is not None:
            display(df)

        md_lines = (table.export_to_markdown(doc) or "").splitlines()
        if md_lines:
            shown = md_lines[:TABLE_MD_LINES]
            if len(md_lines) > TABLE_MD_LINES:
                shown.append(f"| … ({len(md_lines) - TABLE_MD_LINES}줄 생략) |")
            display(Markdown("\n".join(shown)))
        print()

==============================================================================
TABLE 1 — 법인카드_사용규정
==============================================================================
Page        : 1
Rows        : 3
Columns     : 2
Header      : Not detected (header rows=0, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

       0             1
0   제정일   2026. 7. 20.
1   시행일    2026. 8. 1.
2  소관부서         경영지원본부

| 제정일    | 2026. 7. 20.   |
|-----------|----------------|
| 시행일    | 2026. 8. 1.    |
| 소관부서  | 경영지원본부   |

==============================================================================
TABLE 2 — 법인카드_사용규정
==============================================================================
Page        : 7
Rows        : 6
Columns     : 4
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)
Caption     : 별표 1. 직책별 법인카드 사용 한도 개정 v1.1

           직책   1일 한도      월 한도  건당 사전승인 기준
0        대표이사   300만원   1,000만원    100만원 초과
1         본부장   250만원     800만원     80만원 초과
2         부서장   150만원     500만원     60만원 초과
3          팀장   100만원     400만원     50만원 초과
4  비직책자(공용카드)    50만원     200만원     30만원 초과

별표 1. 직책별 법인카드 사용 한도 개정 v1.1

| 직책               | 1일 한도    | 월 한도    | 건당 사전승인 기준   |
|--------------------|-------------|------------|----------------------|
| 대표이사           | 300만원     | 1,000만원  | 100만원 초과         |
| 본부장             | 250만원     | 800만원    | 80만원 초과          |
| 부서장             | 150만원     | 500만원    | 60만원 초과          |
| 팀장               | 100만원     | 400만원    | 50만원 초과          |
| 비직책자(공용카드) | 50만원      | 200만원    | 30만원 초과          |

==============================================================================
TABLE 1 — 부서소개
==============================================================================
Page        : 2
Rows        : 6
Columns     : 5
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

      부서                   주요 역할                                       핵심 업무                    주요 산출물                   협업 부서
0    인사부         채용·인력운영· 조직문화 관리  채용기획/실행, 평가·보상 운 영, 교육체계 설계, 조직문화 프 로그램 운영  채용계획서, 평가 결과보고서, 교육 이수현황  전략기획부(인력 계획), 각 사업본 부
1   재무회계부  회계처리·자금관 리·법인카드 정 산 총괄         결산, 세무신고, 자금운용, 법인 카드 정산·승인 프로세스 운영     재무제표, 정산보 고서, 자금운용계 획              전 부서, 감사실
2  총무구매부             사무환경 및 자산 관리                   구매계약, 시설관리, 복리후생 운영, 사내행사    구매계약서, 자산 대장, 시설점검보 고서            IT운영부, 인사 부
3    법무부                법률리스크 관리            계약검토, 지적재산권관리, 소 송대응, 개인정보 등 규제대응          계약검토의견서, 법률자문보고서          영업본부, AI사 업본부
4  IT운영부        사내 IT 인프라 및 보안 운영            그룹웨어/ERP 운영, 계정권한 관리, 보안정책, 장애대응     시스템운영현황보 고서, 보안점검보 고서            클라우드부, 전 부서

| 부서       | 주요 역할                              | 핵심 업무                                                              | 주요 산출물                                | 협업 부서                           |
|------------|----------------------------------------|------------------------------------------------------------------------|--------------------------------------------|-------------------------------------|
| 인사부     | 채용·인력운영· 조직문화 관리           | 채용기획/실행, 평가·보상 운 영, 교육체계 설계, 조직문화 프 로그램 운영 | 채용계획서, 평가 결과보고서, 교육 이수현황 | 전략기획부(인력 계획), 각 사업본 부 |
| 재무회계부 | 회계처리·자금관 리·법인카드 정 산 총괄 | 결산, 세무신고, 자금운용, 법인 카드 정산·승인 프로세스 운영            | 재무제표, 정산보 고서, 자금운용계 획       | 전 부서, 감사실                     |
| 총무구매부 | 사무환경 및 자산 관리                  | 구매계약, 시설관리, 복리후생 운영, 사내행사                            | 구매계약서, 자산 대장, 시설점검보 고서     | IT운영부, 인사 부                   |
| 법무부     | 법률리스크 관리                        | 계약검토, 지적재산권관리, 소 송대응, 개인정보 등 규제대응              | 계약검토의견서, 법률자문보고서             | 영업본부, AI사 업본부               |
| IT운영부   | 사내 IT 인프라 및 보안 운영            | 그룹웨어/ERP 운영, 계정권한 관리, 보안정책, 장애대응                   | 시스템운영현황보 고서, 보안점검보 고서     | 클라우드부, 전 부서                 |

==============================================================================
TABLE 2 — 부서소개
==============================================================================
Page        : 2
Rows        : 3
Columns     : 5
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

       부서                주요 역할                                   핵심 업무                      주요 산출물                 협업 부서
0  AI플랫폼부     LLM/AI서비스 개발 및 운영  모델 파인튜닝/서빙, AI서비스 기획개발, MLOps 파이프라인 운영         AI서비스 릴리즈, 모델 성능리포트  데이터부, 클라 우드부(매트릭 스)
1     데이터부  데이터 파이프 라인 구축 및 분 석             데이터 수집/정제, 데이터 품질 관리, BI/분석  데이터파이프라인, 분 석리포트, 데이터품질 지표      AI플랫폼부, 플 랫폼개발부

| 부서       | 주요 역할                        | 핵심 업무                                                    | 주요 산출물                                    | 협업 부서                        |
|------------|----------------------------------|--------------------------------------------------------------|------------------------------------------------|----------------------------------|
| AI플랫폼부 | LLM/AI서비스 개발 및 운영        | 모델 파인튜닝/서빙, AI서비스 기획개발, MLOps 파이프라인 운영 | AI서비스 릴리즈, 모델 성능리포트               | 데이터부, 클라 우드부(매트릭 스) |
| 데이터부   | 데이터 파이프 라인 구축 및 분 석 | 데이터 수집/정제, 데이터 품질 관리, BI/분석                  | 데이터파이프라인, 분 석리포트, 데이터품질 지표 | AI플랫폼부, 플 랫폼개발부        |

==============================================================================
TABLE 1 — 업무추진비_사용규정
==============================================================================
Page        : 6
Rows        : 4
Columns     : 3
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

            구분                           1인당 한도                 비고
0          음식물                          50,000원   회사가 제공하는 식사·다과 등
1           선물   50,000원(농수산물·농수산가공품은 150,000원)           물품·상품권 등
2  경조사비(화환 포함)         50,000원(화환·조화는 100,000원)          축의금·조의금 등

| 구분                | 1인당 한도                                  | 비고                         |
|---------------------|---------------------------------------------|------------------------------|
| 음식물              | 50,000원                                    | 회사가 제공하는 식사·다과 등 |
| 선물                | 50,000원(농수산물·농수산가공품은 150,000원) | 물품·상품권 등               |
| 경조사비(화환 포함) | 50,000원(화환·조화는 100,000원)             | 축의금·조의금 등             |

==============================================================================
TABLE 2 — 업무추진비_사용규정
==============================================================================
Page        : 6
Rows        : 5
Columns     : 2
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

          접대 유형                         필수 확인 사항
0      식사·다과 접대    참석자 명단, 업무 관련성, 3만원 초과 시 적격증빙
1         선물 접대     청탁금지법 적용대상자 포함 여부, 별표1 한도 준수
2  행사성 접대(골프 등)     부서장 사전승인, 참석자 명단, 행사 목적 소명자료
3    경조사 화환·조의금   청첩장·부고장 등 소명자료, 20만원 초과 시 적격증빙

| 접대 유형            | 필수 확인 사항                                     |
|----------------------|----------------------------------------------------|
| 식사·다과 접대       | 참석자 명단, 업무 관련성, 3만원 초과 시 적격증빙   |
| 선물 접대            | 청탁금지법 적용대상자 포함 여부, 별표1 한도 준수   |
| 행사성 접대(골프 등) | 부서장 사전승인, 참석자 명단, 행사 목적 소명자료   |
| 경조사 화환·조의금   | 청첩장·부고장 등 소명자료, 20만원 초과 시 적격증빙 |

==============================================================================
TABLE 1 — 조직도
==============================================================================
Page        : 2
Rows        : 8
Columns     : 2
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)
Caption     : 1. 회사 개요

      항목                                                                      내용
0    회사명                                                   타이거 주식회사 (Tiger Inc.)
1     업종                                          B2B SaaS / AI / 클라우드 / 데이터 플랫폼
2   설립연도                                                  2015년 (설립 12년 차, 중견기업)
3  임직원 수                                                                약 1,050명
4   연 매출                                                  약 1,200억원 (연결 기준, 가정치)
5  본사 위치                                                             서울 판교 테크노밸리
6  기업 특징   사업본부별 독립 손익 운영(BU제), AI사업본부-플랫폼사업본부 간 매트릭스(점선보고) 협업, CEO 직속 경영회의체 ...

1. 회사 개요

| 항목      | 내용                                                                                                                                        |
|-----------|---------------------------------------------------------------------------------------------------------------------------------------------|
| 회사명    | 타이거 주식회사 (Tiger Inc.)                                                                                                                |
| 업종      | B2B SaaS / AI / 클라우드 / 데이터 플랫폼                                                                                                    |
| 설립연도  | 2015년 (설립 12년 차, 중견기업)                                                                                                             |
| 임직원 수 | 약 1,050명                                                                                                                                  |
| 연 매출   | 약 1,200억원 (연결 기준, 가정치)                                                                                                            |
| 본사 위치 | 서울 판교 테크노밸리                                                                                                                        |
| 기업 특징 | 사업본부별 독립 손익 운영(BU제), AI사업본부-플랫폼사업본부 간 매트릭스(점선보고) 협업, CEO 직속 경영회의체 + 감사실의 독립적 통제 기능 병행 |

==============================================================================
TABLE 2 — 조직도
==============================================================================
Page        : 4
Rows        : 2
Columns     : 2
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

      항목         내용
0  임직원 수   약 1,050명

| 항목      | 내용       |
|-----------|------------|
| 임직원 수 | 약 1,050명 |

==============================================================================
TABLE 1 — 조직설계_상세기획서
==============================================================================
Page        : 2
Rows        : 9
Columns     : 2
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

      항목                                                                      내용
0    회사명                                                   타이거 주식회사 (Tiger Inc.)
1     업종                                          B2B SaaS / AI / 클라우드 / 데이터 플랫폼
2   설립연도                                                  2015년 (설립 12년 차, 중견기업)
3  임직원 수                                                                약 1,050명
4   연 매출                                                  약 1,200억원 (연결 기준, 가정치)
5  본사 위치                                                             서울 판교 테크노밸리
6  주요 사업   ① 기업용 생성형 AI 플랫폼(LLM 기반 업무자동화 솔루션), ② 클라우드 인프라/DevOps 플랫폼, ③ 데이터 분...
7   기업 특징  사업본부별 독립 손익 운영(BU제) 체제로 각 본부장이 매출·비용에 대한 책임을 지며, 영업/고객성 공 조직은 출장·대...

| 항목      | 내용                                                                                                                                                                                                                                                                                                                                                                                                                |
|-----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 회사명    | 타이거 주식회사 (Tiger Inc.)                                                                                                                                                                                                                                                                                                                                                                                        |
| 업종      | B2B SaaS / AI / 클라우드 / 데이터 플랫폼                                                                                                                                                                                                                                                                                                                                                                            |
| 설립연도  | 2015년 (설립 12년 차, 중견기업)                                                                                                                                                                                                                                                                                                                                                                                     |
| 임직원 수 | 약 1,050명                                                                                                                                                                                                                                                                                                                                                                                                          |
| 연 매출   | 약 1,200억원 (연결 기준, 가정치)                                                                                                                                                                                                                                                                                                                                                                                    |
| 본사 위치 | 서울 판교 테크노밸리                                                                                                                                                                                                                                                                                                                                                                                                |
| 주요 사업 | ① 기업용 생성형 AI 플랫폼(LLM 기반 업무자동화 솔루션), ② 클라우드 인프라/DevOps 플랫폼, ③ 데이터 분석·통합 SaaS, ④ 공공·금융권 대상 B2B 플랫폼 구축                                                                                                                                                                                                                                                                 |
| 기업 특징 | 사업본부별 독립 손익 운영(BU제) 체제로 각 본부장이 매출·비용에 대한 책임을 지며, 영업/고객성 공 조직은 출장·대면영업이 잦고 AI/클라우드 조직은 GPU·클라우드 종량제 비용이 크다는 점에서 조직마다 비용구조가 뚜렷이 다름. AI사업본부와 플랫폼사업본부 사이에는 인프라 운영을 공동 수행 하는 매트릭스(점선보고) 협업 라인이 존재하며, 전사 의사결정은 CEO 직속 경영회의체와 감사실의 독립적 통제 기능이 병행되는 구조 |

==============================================================================
TABLE 2 — 조직설계_상세기획서
==============================================================================
Page        : 5
Rows        : 11
Columns     : 5
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

       조직                  주요 역할                                      핵심 업무                       주요 산출물                          협업 부서
0     감사실         전사 내부통제 및 감사 총괄    정기/수시 감사, 컴플라이언 스 점검, 재무회계부 자체사 용건 사후검증  감사보고서, 시정 조치 권고안, 내 부통제 점검표                   재무회계부, 전 부서
1     인사부        채용·인력운영 ·조직문화 관리  채용기획/실행, 평가·보상 운영, 교육체계 설계, 조직문 화 프로그램 운영     채용계획서, 평가 결과보고서, 교육 이수현황           전략기획부(인력계획), 각 사업본부
2    재무회계부  회계처리·자금 관리·법인카드 정산 총괄        결산, 세무신고, 자금운용, 법 인카드 정산·승인 프로세스 운영        재무제표, 정산보 고서, 자금운용계 획                     전 부서, 감사실
3   총무구매부            사무환경 및 자 산관리                 구매계약, 시설관리, 복리후 생 운영, 사내행사       구매계약서, 자산 대장, 시설점검보 고서                    IT운영부, 인사부
4     법무부               법률리스크 관 리          계약검토, 지적재산권관리, 소송대응, 개인정보 등 규제 대응            계약검토의견서, 법률자문보고서                   영업본부, AI사업본부
5   IT운영부       사내 IT 인프라 및 보안 운영           그룹웨어/ERP 운영, 계정권 한관리, 보안정책, 장애대응        시스템운영현황 보고서, 보안점검 보고서                   클라우드부, 전 부서
6  AI플랫폼부       LLM/AI서비스 개발 및 운영   모델 파인튜닝/서빙, AI서비 스 기획개발, MLOps 파이프 라인 운영          AI서비스 릴리즈, 모델 성능리포트            데이터부, 클라우드부 (매트릭스)
7     데이터부    데이터 파이프 라인 구축 및 분 석                데이터 수집/정제, 데이터 품 질관리, BI/분석    데이터파이프라 인, 분석리포트, 데이터품질지표               AI플랫폼부, 플랫폼개 발부
8   플랫폼개발부     SaaS 플랫폼 기획·개발·운 영         서비스 기획, Backend/ Frontend 개발, 배포운영         플랫폼 릴리즈노 트, 서비스 로드 맵                 클라우드부, 고객성공 부
9    클라우드부     클라우드 인프 라 및 운영자동 화                 인프라 설계/운영, 비용최적 화, 네트워크/보안           인프라 아키텍처 문서, 비용리포트  AI플랫폼부(매트릭스), 플랫폼개발부, IT운영 부

| 조직         | 주요 역할                             | 핵심 업무                                                             | 주요 산출물                                    | 협업 부서                                     |
|--------------|---------------------------------------|-----------------------------------------------------------------------|------------------------------------------------|-----------------------------------------------|
| 감사실       | 전사 내부통제 및 감사 총괄            | 정기/수시 감사, 컴플라이언 스 점검, 재무회계부 자체사 용건 사후검증   | 감사보고서, 시정 조치 권고안, 내 부통제 점검표 | 재무회계부, 전 부서                           |
| 인사부       | 채용·인력운영 ·조직문화 관리          | 채용기획/실행, 평가·보상 운영, 교육체계 설계, 조직문 화 프로그램 운영 | 채용계획서, 평가 결과보고서, 교육 이수현황     | 전략기획부(인력계획), 각 사업본부             |
| 재무회계부   | 회계처리·자금 관리·법인카드 정산 총괄 | 결산, 세무신고, 자금운용, 법 인카드 정산·승인 프로세스 운영           | 재무제표, 정산보 고서, 자금운용계 획           | 전 부서, 감사실                               |
| 총무구매부   | 사무환경 및 자 산관리                 | 구매계약, 시설관리, 복리후 생 운영, 사내행사                          | 구매계약서, 자산 대장, 시설점검보 고서         | IT운영부, 인사부                              |
| 법무부       | 법률리스크 관 리                      | 계약검토, 지적재산권관리, 소송대응, 개인정보 등 규제 대응             | 계약검토의견서, 법률자문보고서                 | 영업본부, AI사업본부                          |
| IT운영부     | 사내 IT 인프라 및 보안 운영           | 그룹웨어/ERP 운영, 계정권 한관리, 보안정책, 장애대응                  | 시스템운영현황 보고서, 보안점검 보고서         | 클라우드부, 전 부서                           |
| AI플랫폼부   | LLM/AI서비스 개발 및 운영             | 모델 파인튜닝/서빙, AI서비 스 기획개발, MLOps 파이프 라인 운영        | AI서비스 릴리즈, 모델 성능리포트               | 데이터부, 클라우드부 (매트릭스)               |
| 데이터부     | 데이터 파이프 라인 구축 및 분 석      | 데이터 수집/정제, 데이터 품 질관리, BI/분석                           | 데이터파이프라 인, 분석리포트, 데이터품질지표  | AI플랫폼부, 플랫폼개 발부                     |
| 플랫폼개발부 | SaaS 플랫폼 기획·개발·운 영           | 서비스 기획, Backend/ Frontend 개발, 배포운영                         | 플랫폼 릴리즈노 트, 서비스 로드 맵             | 클라우드부, 고객성공 부                       |
| 클라우드부   | 클라우드 인프 라 및 운영자동 화       | 인프라 설계/운영, 비용최적 화, 네트워크/보안                          | 인프라 아키텍처 문서, 비용리포트               | AI플랫폼부(매트릭스), 플랫폼개발부, IT운영 부 |

==============================================================================
TABLE 1 — 직급체계
==============================================================================
Page        : 2
Rows        : 7
Columns     : 4
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : Detected (1)
Empty Cell  : 0  (fill rate 100.0%)

   직급                  역할                   책임  보임 가능 직책
0  사원     실무 수행, 기본 업무 처리            배정된 과업의 완수       없음
1  주임   실무 수행 및 후배 사원 가이드         담당 업무의 품질 관리        없음
2  대리       담당 업무의 독립적 수행         프로젝트/과업 단위 책임       없음
3  과장      소규모 팀 또는 파트 리드         팀 성과 및 일정 관리        팀장
4  차장      팀/파트 리드, 중간관리자    복수 프로젝트 총괄, 후배 육성        팀장
5  부장               부서 총괄   부서 성과, 예산, 인력관리 책임   팀장, 부서장

| 직급    | 역할                          | 책임                           | 보임 가능 직책   |
|---------|-------------------------------|--------------------------------|------------------|
| 사원    | 실무 수행, 기본 업무 처리     | 배정된 과업의 완수             | 없음             |
| 주임    | 실무 수행 및 후배 사원 가이드 | 담당 업무의 품질 관리          | 없음             |
| 대리    | 담당 업무의 독립적 수행       | 프로젝트/과업 단위 책임        | 없음             |
| 과장    | 소규모 팀 또는 파트 리드      | 팀 성과 및 일정 관리           | 팀장             |
| 차장    | 팀/파트 리드, 중간관리자      | 복수 프로젝트 총괄, 후배 육성  | 팀장             |
| 부장    | 부서 총괄                     | 부서 성과, 예산, 인력관리 책임 | 팀장, 부서장     |

==============================================================================
TABLE 2 — 직급체계
==============================================================================
Page        : 3
Rows        : 5
Columns     : 4
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

          직급                      역할                   책임       보임 가능 직책
0         이사        본부 내 사업/기능 총괄 보좌      본부 전략 실행, 대외 협상    부서장, 본부장 대행
1         상무                 사업본부 총괄   본부 손익, 인력·예산 운영 전권            본부장
2         전무   복수 본부 총괄 또는 CEO 직속 임원       전사 전략 방향 수립 참여   본부장, 복수본부 총괄
3  대표이사(CEO)                회사 경영 총괄       전사 경영성과, 대외 대표    대표이사(해당 없음)

| 직급          | 역할                              | 책임                           | 보임 가능 직책        |
|---------------|-----------------------------------|--------------------------------|-----------------------|
| 이사          | 본부 내 사업/기능 총괄 보좌       | 본부 전략 실행, 대외 협상      | 부서장, 본부장 대행   |
| 상무          | 사업본부 총괄                     | 본부 손익, 인력·예산 운영 전권 | 본부장                |
| 전무          | 복수 본부 총괄 또는 CEO 직속 임원 | 전사 전략 방향 수립 참여       | 본부장, 복수본부 총괄 |
| 대표이사(CEO) | 회사 경영 총괄                    | 전사 경영성과, 대외 대표       | 대표이사(해당 없음)   |

==============================================================================
TABLE 1 — 출장비_사용규정
==============================================================================
Page        : 1
Rows        : 3
Columns     : 2
Header      : Not detected (header rows=0, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

       0               1
0   제정일     2026. 7. 20.
1   시행일      2026. 8. 1.
2  소관부서   경영지원본부 (재무회계부)

| 제정일    | 2026. 7. 20.              |
|-----------|---------------------------|
| 시행일    | 2026. 8. 1.               |
| 소관부서  | 경영지원본부 (재무회계부) |

==============================================================================
TABLE 2 — 출장비_사용규정
==============================================================================
Page        : 5
Rows        : 3
Columns     : 4
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

            구분        일비    식비(1일)  숙박비 상한(1박)
0     국내출장(당일)   20,000원   30,000원           -
1  국내출장(1박 이상)   20,000원   30,000원    150,000원

| 구분               | 일비     | 식비(1일)    | 숙박비 상한(1박)   |
|--------------------|----------|--------------|--------------------|
| 국내출장(당일)     | 20,000원 | 30,000원     | -                  |
| 국내출장(1박 이상) | 20,000원 | 30,000원     | 150,000원          |

==============================================================================
TABLE 1 — 회식_운영규정
==============================================================================
Page        : 2
Rows        : 9
Columns     : 3
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : Detected (2)
Empty Cell  : 0  (fill rate 100.0%)

             유형                                                  정의                          비용 항목 분류(제15조 준용)
0       ① 공식 회식      부서·본부 단위로 사전 계획되어 관리자 주관 하에 개최되는 정기·비정기 행사성 회식                                   복리후생비 원칙
1        ② 팀 회식                           팀 단위로 팀장 주관 하에 개최되는 소규모 회식                                  복리후생비 원칙
2     ③ 프로젝트 회식   특정 프로젝트(TF 포함) 참여 인원을 대상으로 착 수·마일스톤·종료 시점에 개최되는 회식  복리후생비 원칙(외부 파트너 동석 시 기 업업무추진비로 전환될 수 있음)
3      ④ 워크숍 식사                    워크숍·세미나 등 사전 승인된 행사 프로그램에 포 함된 식사              회의비 또는 복리후생비(제15조 3호·2 호 준용)
4  ⑤ 신규 입사자 환 영회                 신규 입사자를 대상으로 소속 팀·부서가 개최하는 환영 목적 회식                                     복리후생비
5     ⑥ 퇴사자 송별회                퇴사(예정)자를 대상으로 소속 팀·부서가 개최하 는 송별 목적 회식                                     복리후생비
6  ⑦ 성과 달성 축하 회식                   프로젝트 종료, 계약 수주, 목표 달성 등을 기념하 는 회식                  복리후생비(거래처 동석 시 기업업무추 진비)
7   ⑧ 거래처 동반 회 식                             협력사·고객사 등 외부인이 참석하는 회식                           기업업무추진비(제15조 1호)

| 유형                  | 정의                                                                                 | 비용 항목 분류(제15조 준용)                                           |
|-----------------------|--------------------------------------------------------------------------------------|-----------------------------------------------------------------------|
| ① 공식 회식           | 부서·본부 단위로 사전 계획되어 관리자 주관 하에 개최되는 정기·비정기 행사성 회식     | 복리후생비 원칙                                                       |
| ② 팀 회식             | 팀 단위로 팀장 주관 하에 개최되는 소규모 회식                                        | 복리후생비 원칙                                                       |
| ③ 프로젝트 회식       | 특정 프로젝트(TF 포함) 참여 인원을 대상으로 착 수·마일스톤·종료 시점에 개최되는 회식 | 복리후생비 원칙(외부 파트너 동석 시 기 업업무추진비로 전환될 수 있음) |
| ④ 워크숍 식사         | 워크숍·세미나 등 사전 승인된 행사 프로그램에 포 함된 식사                            | 회의비 또는 복리후생비(제15조 3호·2 호 준용)                          |
| ⑤ 신규 입사자 환 영회 | 신규 입사자를 대상으로 소속 팀·부서가 개최하는 환영 목적 회식                        | 복리후생비                                                            |
| ⑥ 퇴사자 송별회       | 퇴사(예정)자를 대상으로 소속 팀·부서가 개최하 는 송별 목적 회식                      | 복리후생비                                                            |
| ⑦ 성과 달성 축하 회식 | 프로젝트 종료, 계약 수주, 목표 달성 등을 기념하 는 회식                              | 복리후생비(거래처 동석 시 기업업무추 진비)                            |
| ⑧ 거래처 동반 회 식   | 협력사·고객사 등 외부인이 참석하는 회식                                              | 기업업무추진비(제15조 1호)                                            |

==============================================================================
TABLE 2 — 회식_운영규정
==============================================================================
Page        : 3
Rows        : 5
Columns     : 5
Header      : Detected (header rows=1, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 100.0%)

   회식 단위                     개최(주관)              참석 범위  1차 승 인권자                                                                      비고
0   팀 회식                         팀장        팀원 전원 또는 일부        팀장                                   팀장 본인이 카드 사용자인 경우 부서장이 최종 승인(자기승인 방지)
1  부서 회식                         부서장   부서 전체 또는 복수 팀 합동      부서장                                부서장 본인이 사용자인 경우 본부장(경영지원본 부는 CEO)이 최종 승인
2  본부 회식                         본부장  본부 전체 또는 복수 부서 합동       본부장  본부장 본인이 사용자인 경우 CEO가 최종 승인. 경영지원본부는 본부장 직위가 없으므로 소관 부 서장이 개최하고 CEO...
3   전사 회식  CEO 또는 경영지 원본부(총무구매 부) 주관            전사 임직원        CEO                                        전사 공지 및 예산 편성 필요, 사전승인 필수(제9 조)

| 회식 단위    | 개최(주관)                               | 참석 범위                     | 1차 승 인권자    | 비고                                                                                                                  |
|--------------|------------------------------------------|-------------------------------|------------------|-----------------------------------------------------------------------------------------------------------------------|
| 팀 회식      | 팀장                                     | 팀원 전원 또는 일부           | 팀장             | 팀장 본인이 카드 사용자인 경우 부서장이 최종 승인(자기승인 방지)                                                      |
| 부서 회식    | 부서장                                   | 부서 전체 또는 복수 팀 합동   | 부서장           | 부서장 본인이 사용자인 경우 본부장(경영지원본 부는 CEO)이 최종 승인                                                   |
| 본부 회식    | 본부장                                   | 본부 전체 또는 복수 부서 합동 | 본부장           | 본부장 본인이 사용자인 경우 CEO가 최종 승인. 경영지원본부는 본부장 직위가 없으므로 소관 부 서장이 개최하고 CEO가 승인 |
| 전사 회식    | CEO 또는 경영지 원본부(총무구매 부) 주관 | 전사 임직원                   | CEO              | 전사 공지 및 예산 편성 필요, 사전승인 필수(제9 조)                                                                    |

==============================================================================
TABLE 1 — 법인세법
==============================================================================
Page        : 14
Rows        : 0
Columns     : 0
Header      : Not detected (header rows=0, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 0.0%)
Note        : 표 영역만 검출 · 셀 구조 복원 실패 (0x0)

Empty DataFrame
Columns: []
Index: []

==============================================================================
TABLE 2 — 법인세법
==============================================================================
Page        : 20
Rows        : 0
Columns     : 0
Header      : Not detected (header rows=0, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 0.0%)
Note        : 표 영역만 검출 · 셀 구조 복원 실패 (0x0)

Empty DataFrame
Columns: []
Index: []

==============================================================================
TABLE 1 — 부가가치세법
==============================================================================
Page        : 5
Rows        : 0
Columns     : 0
Header      : Not detected (header rows=0, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 0.0%)
Note        : 표 영역만 검출 · 셀 구조 복원 실패 (0x0)

Empty DataFrame
Columns: []
Index: []

==============================================================================
TABLE 2 — 부가가치세법
==============================================================================
Page        : 19
Rows        : 0
Columns     : 0
Header      : Not detected (header rows=0, multi=N, row-header=N)
Merged Cell : None
Empty Cell  : 0  (fill rate 0.0%)
Note        : 표 영역만 검출 · 셀 구조 복원 실패 (0x0)

Empty DataFrame
Columns: []
Index: []

---
## 7. 전체 결과 요약

세 평가 영역(Layout / Hierarchy / Table)을 한 화면에서 확인한다.
문서별 수치는 `summary_df`(→ `output/summary.csv`)에 있다.

In [10]:
def _count(name: str, etype: str) -> int:
    return int(((layout_df["Document"] == name) & (layout_df["Element Type"] == etype)).sum())


summary_rows = []
for name in DOCS:
    conv = conversion_df.loc[conversion_df["Document"] == name].iloc[0]
    metrics = hierarchy_metrics(name)
    doc_tables = tables_df[tables_df["Document"] == name] if not tables_df.empty else pd.DataFrame()
    summary_rows.append({
        "Document": name,
        "Folder": conv["Folder"],
        "Pages": int(conv["Pages"]),
        "Status": conv["Status"],
        "Sec": conv["Sec"],
        "Elements": int((layout_df["Document"] == name).sum()),
        "Title": _count(name, "Title"),
        "Heading": _count(name, "Heading"),
        "Text": _count(name, "Text"),
        "List": _count(name, "List"),
        "Table": _count(name, "Table"),
        "Picture": _count(name, "Picture"),
        "Header/Footer": _count(name, "Header") + _count(name, "Footer"),
        "Max Level": metrics["Max Level"],
        "Level Jumps": metrics["Level Jumps"],
        "Flat?": metrics["Flat?"],
        "Tables Converted": int(len(doc_tables)),
        "Tables 0x0": int((doc_tables["Cells"] == 0).sum()) if len(doc_tables) else 0,
        "Table Rows": int(doc_tables["Rows"].sum()) if len(doc_tables) else 0,
        "Merged Cells": int(doc_tables["Merged Cells"].sum()) if len(doc_tables) else 0,
        "Header Detected": int((doc_tables["Header"] == "Detected").sum()) if len(doc_tables) else 0,
    })

summary_df = pd.DataFrame(summary_rows)
summary_df.to_csv(OUTPUT_DIR / "summary.csv", index=False, encoding="utf-8-sig")

_levels = (
    hierarchy_df[hierarchy_df["Type"].isin(HEADING_TYPES) & hierarchy_df["Level"].ne("")]["Level"]
    .value_counts().sort_index()
)

print("=" * 78)
print("DOCLING PARSING TEST SUMMARY")
print("=" * 78)
print(f"Documents          : {len(DOCS)} / {len(PDF_PATHS)} 변환 성공")
print(f"Pages              : {int(summary_df['Pages'].sum())}")
print(f"Elapsed            : {summary_df['Sec'].sum():.1f}s")

print("\n[1] Layout Analysis")
print("-" * 40)
for _t, _c in layout_df["Element Type"].value_counts().items():
    print(f"{_t:<18} : {_c}")

print("\n[2] Text Hierarchy")
print("-" * 40)
print(f"{'Heading detected':<18} : {int(_levels.sum())}")
for _lvl, _c in _levels.items():
    print(f"{_lvl:<18} : {_c}")
print(f"{'Level jumps':<18} : {int(summary_df['Level Jumps'].sum())}")
print(f"{'Flat documents':<18} : {int((summary_df['Flat?'] != 'no').sum())} / {len(summary_df)}")

print("\n[3] Table Structure")
print("-" * 40)
if tables_df.empty:
    print("Tables detected    : 0")
else:
    _structured = tables_df[tables_df["Cells"] > 0]
    print(f"{'Tables detected':<18} : {len(tables_df)}")
    print(f"{'Tables converted':<18} : {len(table_frames)}")
    print(f"{'Structure OK':<18} : {len(_structured)} / {len(tables_df)}"
          f"   (0x0 = 영역만 검출: {len(tables_df) - len(_structured)})")
    print(f"{'Rows reconstructed':<18} : {int(tables_df['Rows'].sum())}")
    print(f"{'Columns (max)':<18} : {int(tables_df['Cols'].max())}")
    print(f"{'Header detected':<18} : {int((tables_df['Header'] == 'Detected').sum())} / {len(tables_df)}")
    print(f"{'Multi header':<18} : {int((tables_df['Multi Header'] == 'Y').sum())}")
    print(f"{'Merged cells':<18} : {int(tables_df['Merged Cells'].sum())}")
    print(f"{'Mean fill rate':<18} : "
          f"{_structured['Fill Rate'].mean():.1%} (0x0 제외 {len(_structured)}건 기준)")

print("\n[문서별 요약]")
display(summary_df)

==============================================================================
DOCLING PARSING TEST SUMMARY
==============================================================================
Documents          : 11 / 11 변환 성공
Pages              : 222
Elapsed            : 23.2s

[1] Layout Analysis
----------------------------------------
List               : 2432
Text               : 738
Heading            : 493
Footer             : 431
Header             : 214
Table              : 54
Code               : 14
Picture            : 7
Formula            : 3
Caption            : 2

[2] Text Hierarchy
----------------------------------------
Heading detected   : 493
H1                 : 138
H2                 : 355
Level jumps        : 0
Flat documents     : 3 / 11

[3] Table Structure
----------------------------------------
Tables detected    : 54
Tables converted   : 54
Structure OK       : 47 / 54   (0x0 = 영역만 검출: 7)
Rows reconstructed : 224
Columns (max)      : 7
Header detected    : 45 / 54
Multi header       : 0
Merged cells       : 8
Mean fill rate     : 100.0% (0x0 제외 47건 기준)

[문서별 요약]

,Document,Folder,Pages,Status,Sec,Elements,Title,Heading,Text,List,...,Picture,Header/Footer,Max Level,Level Jumps,Flat?,Tables Converted,Tables 0x0,Table Rows,Merged Cells,Header Detected
0,법인카드_사용규정,pdf,7,SUCCESS,3.8,120,0,28,11,60,...,0,18,2,0,no,2,0,9,0,1
1,부서소개,pdf,5,SUCCESS,1.2,32,0,9,1,0,...,0,13,1,0,YES (계층 없음),9,0,36,2,9
2,업무추진비_사용규정,pdf,6,SUCCESS,0.5,101,0,25,18,41,...,0,15,2,0,no,2,0,9,0,2
3,조직도,pdf,6,SUCCESS,0.6,42,0,9,3,9,...,1,15,1,0,YES (계층 없음),4,0,18,0,4
4,조직설계_상세기획서,pdf,12,SUCCESS,2.0,101,0,23,7,25,...,1,33,2,0,no,12,0,68,3,12
5,직급체계,pdf,4,SUCCESS,0.6,31,0,6,3,9,...,0,10,1,0,YES (계층 없음),3,0,17,1,3
6,출장비_사용규정,pdf,6,SUCCESS,0.6,83,0,24,12,28,...,0,15,2,0,no,4,0,11,0,3
7,회식_운영규정,pdf,10,SUCCESS,2.0,105,0,21,24,21,...,0,28,2,0,no,11,0,56,2,11
8,법인세법,law,97,SUCCESS,7.6,2098,0,188,387,1216,...,3,291,2,0,no,4,4,0,0,0
9,부가가치세법,law,35,SUCCESS,1.9,767,0,57,105,493,...,1,105,2,0,no,3,3,0,0,0
10,여신전문금융업법,law,34,SUCCESS,2.4,908,0,103,167,530,...,1,102,2,0,no,0,0,0,0,0

---
## 8. Markdown 결과 저장

문서별 Markdown은 `output/markdown/<문서>.md`, 전체를 이어붙인 것은 `output/docling_result.md`에
저장한다. 저장 후 미리보기 문서의 앞부분을 화면에 찍어 계층·표가 Markdown에도 살아 있는지 눈으로 확인한다.

In [11]:
MD_PREVIEW_CHARS = 1200

md_parts, md_rows = [], []
for name, doc in DOCS.items():
    try:
        markdown = doc.export_to_markdown()
    except Exception as exc:  # noqa: BLE001
        print(f"[error] Markdown export 실패: {name} — {type(exc).__name__}: {exc}")
        continue
    (MD_DIR / f"{name}.md").write_text(markdown, encoding="utf-8")
    md_parts.append(f"# {name}\n\n{markdown}")
    md_rows.append({"Document": name, "Chars": len(markdown), "Lines": markdown.count(chr(10)) + 1})

combined_md = "\n\n---\n\n".join(md_parts)
(OUTPUT_DIR / "docling_result.md").write_text(combined_md, encoding="utf-8")

print(f"문서별 Markdown : {MD_DIR.relative_to(BASE_DIR)}/<문서>.md  ({len(md_rows)}건)")
print(f"통합 Markdown   : {(OUTPUT_DIR / 'docling_result.md').relative_to(BASE_DIR)}  "
      f"({len(combined_md):,} chars)")
display(pd.DataFrame(md_rows))

print("\n" + "=" * 78)
print(f"MARKDOWN PREVIEW — {PREVIEW_DOC} (앞 {MD_PREVIEW_CHARS}자)")
print("=" * 78)
print((MD_DIR / f"{PREVIEW_DOC}.md").read_text(encoding="utf-8")[:MD_PREVIEW_CHARS])

문서별 Markdown : output\markdown/<문서>.md  (11건)
통합 Markdown   : output\docling_result.md  (372,301 chars)

      Document   Chars  Lines
0    법인카드_사용규정    6288    168
1         부서소개    5723     73
2   업무추진비_사용규정    6849    148
3          조직도    3754     66
4   조직설계_상세기획서   15446    191
5         직급체계    2859     53
6     출장비_사용규정    5420    128
7      회식_운영규정   15934    192
8         법인세법  188116   2513
9       부가가치세법   64684    889
10    여신전문금융업법   57041   1130

==============================================================================
MARKDOWN PREVIEW — 법인카드_사용규정 (앞 1200자)
==============================================================================
## 타 이 거 주 식 회 사 ( T i ge r I n c . )

## 법인카드 사용 규정

| 제정일    | 2026. 7. 20.   |
|-----------|----------------|
| 시행일    | 2026. 8. 1.    |
| 소관부서  | 경영지원본부   |

개정이력 v1.0 제정 (조문 정합성 검토 반영) / v1.1 개정: 제2조 관리자 정의 정비, 제10조 사전승인 예외절차 신 설, 별표1 이사 겸직·대행 시 한도 적용기준 명확화

※ 본 규정은 데모/교육 목적의 가상 기업(타이거 주식회사, Tiger Inc.) 시나리오용으로 작성되었으며, 회사는 설립 12년차 중견 기업(세법상 중소기업 특례 대상 아님)임을 가정합니다. 연 매출액은 연결 기준 약 1,200억원(500억원 초과 구간)으로 가정하였 으며, 실제 적용 시 회사의 정확한 매출 규모·업종·지주회사 여부 등에 따라 한도 및 조항을 조정해야 합니다.

### 제1조 (목적)

이 규정은 타이거 주식회사(이하 "회사")가 임직원에게 발급하는 법인카드의 발급, 관리, 사용 및 정산에 관 한 사항을 정함으로써 업무 효율성을 높이고, 관계 법령에 따른 손금 인정 요건을 충족하여 세무상 불이익을 방지하며, 법인카드 오남용을 예방하는 것을 목적으로 한다.

### 제2조 (정의) 개정 v1.1

이 규정에서 사용하는 용어의 정의는 다음과 같다.

1. "법인카드"란 회사 명의로 발급되어 임직원이 업무 목적의 지출에 사용하는 신용카드·체크카드를 말한 다.
2. "사용자"란 법인카드를 발급받아 사용하는 임직원을 말한다.
3. "관리자"란 법인카드 정산 승인 권한을 가진 자로서 「직급체계」에 따라 결재권을 보유한 팀장·부서장· 본부장 및 대표이사를 말한다. 법인카드의 발급·회수 등 관리업무는 경영지원본부(인사부·재무회계부·총무 구매부·법무부)가 총괄한다.
4. "담당자"란 법인카드를 발급받아 사용하고 정산을 신청하는 임직원 본인을 말하며, 법인카드 사용 신청· 영수증 업로드·사유 작성 및 반려 시 재상신·이의제기(어필)를 수행하는 자를 말한다(제2호의 "사용자"와 동 일인을 지칭하는 정산 시스템상의 역할 명칭이다). 정산 서류의 1차 확인·처리 업무는 재무회계부(재무회계 팀)가 수행한다.
5. "기업업무추진비"란 회사가 업무와 관련하여 접대·교제·사례 등의 목적으로 지출하는 비용을 말한다(종 전 "접대비").
6. "적격증명서류"란

### 8-1. 생성된 산출물 목록

노트북이 만든 파일은 전부 `docling_eval/output/` 아래에만 있다.

In [12]:
artifacts = sorted(
    (p for p in OUTPUT_DIR.rglob("*") if p.is_file()),
    key=lambda p: p.relative_to(OUTPUT_DIR).as_posix(),
)
artifact_df = pd.DataFrame(
    [
        {"File": p.relative_to(OUTPUT_DIR).as_posix(), "KB": round(p.stat().st_size / 1024, 1)}
        for p in artifacts
    ]
)
print(f"총 {len(artifact_df)}개 파일, {artifact_df['KB'].sum():,.1f} KB  ({OUTPUT_DIR})")
display(artifact_df.head(40))

총 137개 파일, 4,276.1 KB  (D:\project\SKN29-FINAL-1TEAM\docling_eval\output)

                              File      KB
0                docling_result.md   793.2
1   hierarchy/hierarchy_result.csv   852.2
2          hierarchy/법인세법_tree.txt   247.8
3     hierarchy/법인카드_사용규정_tree.txt    11.4
4        hierarchy/부가가치세법_tree.txt    95.5
5          hierarchy/부서소개_tree.txt     0.7
6    hierarchy/업무추진비_사용규정_tree.txt     9.9
7      hierarchy/여신전문금융업법_tree.txt   103.4
8           hierarchy/조직도_tree.txt     2.4
9    hierarchy/조직설계_상세기획서_tree.txt     6.2
10         hierarchy/직급체계_tree.txt     1.7
11     hierarchy/출장비_사용규정_tree.txt     7.9
12      hierarchy/회식_운영규정_tree.txt     7.6
13   layout/layout_by_document.csv     0.7
14       layout/layout_by_page.csv    30.5
15        layout/layout_result.csv  1057.7
16                markdown/법인세법.md   415.2
17           markdown/법인카드_사용규정.md    13.5
18              markdown/부가가치세법.md   145.0
19                markdown/부서소개.md     8.5
20          markdown/업무추진비_사용규정.md    14.6
21            markdown/여신전문금융업법.md   125.7
22                 markdown/조직도.md     5.7
23          markdown/조직설계_상세기획서.md    23.5
24                markdown/직급체계.md     4.6
25            markdown/출장비_사용규정.md    11.0
26             markdown/회식_운영규정.md    25.4
27                     summary.csv     1.1
28        tables/table_summary.csv     3.6
29        tables/법인세법/table_01.csv     0.0
30       tables/법인세법/table_01.json     0.4
31        tables/법인세법/table_02.csv     0.0
32       tables/법인세법/table_02.json     0.4
33        tables/법인세법/table_03.csv     0.0
34       tables/법인세법/table_03.json     0.4
35        tables/법인세법/table_04.csv     0.0
36       tables/법인세법/table_04.json     0.4
37   tables/법인카드_사용규정/table_01.csv     0.1
38  tables/법인카드_사용규정/table_01.json     1.5
39   tables/법인카드_사용규정/table_02.csv     0.3

---
## 최종 판정 — 세 질문에 답하기

```text
┌──────────────────────────────────────┐
│ 1. Layout Analysis                   │
│    → 영역 구분이 정확한가?           │
├──────────────────────────────────────┤
│ 2. Text Hierarchy                    │
│    → 문서 계층이 유지되는가?         │
├──────────────────────────────────────┤
│ 3. Table Structure                   │
│    → 표 구조가 복원되는가?           │
└──────────────────────────────────────┘
```

| 질문 | 어디를 보나 | 나쁨 신호 |
|---|---|---|
| ① 영역 구분 | §4 `layout_by_document` / `layout_totals`, `layout/layout_result.csv` | `Other` 비중이 크다 · Heading이 0인 문서 · 본문이 전부 `Text` 한 덩어리 |
| ② 계층 보존 | §5 `heading_level_df` / `hierarchy_metrics_df`, `hierarchy/<문서>_tree.txt` | `Flat? = YES` · `Level Jumps`가 헤딩 수에 맞먹음 · 트리에서 본문이 엉뚱한 헤딩에 붙음 |
| ③ 표 복원 | §6 `tables_df`, `tables/<문서>/table_NN.json` | `Header = Not detected` 비중이 크다 · `Fill Rate`가 낮다 · Rows/Cols가 원본과 다르다 |

**주의 — 이 노트북이 재는 것과 재지 않는 것.** 여기서 나오는 수치는 전부 Docling의 *자기 보고*다.
원본 PDF와의 대조(정답지 채점)는 하지 않는다. 최종 채택 판단 전에는 `tables/*.csv`와
`hierarchy/*_tree.txt` 몇 건을 원본 PDF와 눈으로 대조하는 단계가 반드시 필요하다.

또한 이 규정 PDF들에는 docling 리딩오더·CJK 줄바꿈·목록 마커 관련 결함이 알려져 있다
(CLAUDE.md 상태 보드 "RAG 문서 파싱(docling)" 행 참조). 그 교정은 이 평가 노트북의 범위 밖이다 —
여기서는 **후처리 없는 날것의 Docling 성능**을 본다.